# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2afb4f7395d1c108afe916b7d67230e264aaaee3a20134286e76062c09dd53abf5902f110a06c0fa57b7d2b19184c818ad1e88dd3519f472a9065c060a80d218

test:
  secret_key_base: 34b7b62262df7e00104616a4c65d02990f2c0ac08ccc682749b46507983284190cadcc34f8cfb17caa0fa0923ad72216e29e7bd1d93066b2603c8034e6cfc8d2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
